<?php

/**
 * BaseProfile_photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $photo_id
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property Photo $Photo
 * 
 * @method integer       getPhotoId()  Returns the current record's "photo_id" value
 * @method integer       getUserId()   Returns the current record's "user_id" value
 * @method sfGuardUser   getUser()     Returns the current record's "User" value
 * @method Photo         getPhoto()    Returns the current record's "Photo" value
 * @method Profile_photo setPhotoId()  Sets the current record's "photo_id" value
 * @method Profile_photo setUserId()   Sets the current record's "user_id" value
 * @method Profile_photo setUser()     Sets the current record's "User" value
 * @method Profile_photo setPhoto()    Sets the current record's "Photo" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile_photo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_photo');
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Photo', array(
             'local' => 'photo_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}