<?php

/**
 * InboxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InboxTable extends PluginInboxTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object InboxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inbox');
    }
}