<?php

/**
 * PubsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPubsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PubsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Pubs');
    }

    public static function activatePub($id=null) {
        Doctrine_Query::create()
                ->update('Pubs p')
                ->set('p.is_active', '?', true)
                ->where('p.id = ?', $id)
                ->execute();
    }
    public static function insertPub($model=null, $id=null, $user=null, $dest=null) {

            $pub = new Pubs();
            $pub->setUserId($user);
            $pub->setDestUserId($dest);
            $pub->setRecordModel($model);
            $pub->setRecordId($id);
            //guardo el objeto
            $pub->save();
            return $pub;
        
    }
    
    public static function getPubs($user) {
        if (!is_numeric($user)) {
            $datos = Doctrine::getTable('sfGuardUser')->findOneBy('username', $user, Doctrine::HYDRATE_RECORD);
        } else {
            $datos = Doctrine::getTable('sfGuardUser')->find($user);
        }
        $w = Doctrine_Query::create()
                ->from('Pubs i')
                ->where('i.user_id = ?', $datos->getId());
        return count($w->execute());
    }

}