<?php

/**
 * PluginAudio_has_playlistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAudio_has_playlistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAudio_has_playlistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAudio_has_playlist');
    }
}