<?php

/**
 * PluginPlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlaylistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlaylistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlaylist');
    }
}