<?php

/**
 * AudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginAudioTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object AudioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Audio');
    }

    public static function deletePublications($params) {
        $q = Doctrine_Query::create()
                ->delete('pubs')
                ->where('record_id=?', $params['audio_id'])
                ->addWhere('record_model=?', 'audio');
        return $q->execute();
    }

}