<?php

/**
 * PluginLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLocation');
    }
    
    public static function insertLocation($user=null, $desc=null) {
        
            $loc = new Location();
            $loc->setUserId($user);
            $loc->setDescription($desc);        
            //guardo el objeto
            $loc->save();
            return $loc;
        
    }
}