<?php

/**
 * Audio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PubsPlugin
 * @subpackage model
 * @author     Dario Sebastian Sasturain <dsastu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginAudio extends BaseAudio {

    public function getFavlikes() {
        $query = Doctrine::getTable('Favlike')->createQuery('p')
                ->where('p.record_id = ?', $this->_get('id'))
                ->andWhere('p.record_model = ?', 'audio')
                ->leftJoin('p.User u')
                ->orderBy('p.created_at DESC');
        return $query->execute();
    }

    public function getComments() {
        $query = Doctrine::getTable('Comment')->createQuery('p')
                ->where('p.record_id = ?', $this->_get('id'))
                ->andWhere('p.record_model = ?', 'audio')
                ->leftJoin('p.User u')
                ->orderBy('p.created_at ASC');
        return $query->execute();
    }
    
    public function getPath() {
        $user = $this->getUser();
        return sfConfig::get('sf_web_dir') . DIRECTORY_SEPARATOR . 'users' . DIRECTORY_SEPARATOR . $user->getUsername() . DIRECTORY_SEPARATOR . 'audios' . DIRECTORY_SEPARATOR;
    }
    
    public function preDelete($event) {
        $path = $this->getPath();
        $audio = $path . DIRECTORY_SEPARATOR . $this->getFilename();
        if (file_exists($audio)) {
            unlink($audio);
        }

//        $this->deleteComments();
        $this->deletePublications();
    }

    public function deletePublications() {
        if (in_array('pubs', sfConfig::get('sf_enabled_modules', array()))) {
            Doctrine::getTable('Audio')->DeletePublications(array('audio_id' => $this->getId()));
        }
    }

}