<?php

/**
 * Setting_has_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginSetting_has_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Setting_has_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Setting_has_User');
    }
     public static function SettingUser($user_id=null, $setting_id=null) {
        $q = Doctrine_Query::create()
                ->from('Setting_has_User f')
                ->where('f.user_id = ?', $user_id)
                ->andWhere('f.setting_id = ?', $setting_id);
        return $q->fetchOne();
    }
}