<?php

/**
 * Favlike
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PubsPlugin
 * @subpackage model
 * @author     Dario Sebastian Sasturain <dsastu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginFavlike extends BaseFavlike {

    public function getObject() {
        $query = Doctrine::getTable($this->_get('record_model'))->createQuery('p')
                ->where('p.id = ?', $this->_get('record_id'));
                if ($this->_get('record_model') != 'photo') {
                   $query->leftJoin('p.User u');
                }
        $query->orderBy('p.created_at DESC');
        return $query->execute();
    }

}