<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comment');
    }
    
    public static function activate($id=null) {
        Doctrine_Query::create()
                ->update('comment c')
                ->set('c.is_active', '?', true)
                ->where('c.id = ?', $id)
                ->execute();
    }
    
    public function countComments($id=null,$model=null)
    {
         $q = Doctrine_Query::create()
                        ->from('Comment c')
                        ->where('c.record_id = ?',$id)
                        ->andWhere('c.record_model = ?',$model);
        return $q->count();
    }
    
    public static function getComments($user) {
        if (!is_numeric($user)) {
            $datos = Doctrine::getTable('sfGuardUser')->findOneBy('username', $user, Doctrine::HYDRATE_RECORD);
        } else {
            $datos = Doctrine::getTable('sfGuardUser')->find($user);
        }
        $w = Doctrine_Query::create()
                ->from('Comment i')
                ->where('i.user_id = ?', $datos->getId());
        return count($w->execute());
    }
}