<?php

/**
 * FollowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginFollowTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object FollowTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Follow');
    }

    public static function getFollowing($user_id=null, $follow_id=null) {
        $q = Doctrine_Query::create()
                ->from('follow f')
                ->where('f.user_id = ?', $user_id)
                ->andWhere('f.follow_id = ?', $follow_id);
        return $q->fetchOne();
    }


}