<?php

/**
 * PluginLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PubsPlugin
 * @subpackage model
 * @author     Dario Sebastian Sasturain <dsastu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginLink extends BaseLink {

    public function getFavlikes() {
        $query = Doctrine::getTable('Favlike')->createQuery('p')
                ->where('p.record_id = ?', $this->_get('id'))
                ->andWhere('p.record_model = ?', 'link')
                ->leftJoin('p.User u')
                ->orderBy('p.created_at DESC');
        return $query->execute();
    }

    public function getComments() {
        $query = Doctrine::getTable('Comment')->createQuery('p')
                ->where('p.record_id = ?', $this->_get('id'))
                ->andWhere('p.record_model = ?', 'link')
                ->leftJoin('p.User u')
                ->orderBy('p.created_at ASC');
        return $query->execute();
    }

}