<?php

/**
 * PluginNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PubsPlugin
 * @subpackage model
 * @author     Dario Sebastian Sasturain <dsastu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginNotification extends BaseNotification
{

}