<?php

/**
 * Album_photoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Album_photoTable extends PluginAlbum_photoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Album_photoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album_photo');
    }
}