<?php

/**
 * Tags_photoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tags_photoTable extends PluginTags_photoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tags_photoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tags_photo');
    }
}