<?php

/**
 * PluginInbox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package     InboxPlugin
 * @subpackage  model
 * @author      Dario Sebastian Sasturain SEBARDO <dsastu@gmail.com>
 */
abstract class PluginInbox extends BaseInbox
{

}