<?php

/**
 * PluginInboxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInboxTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PluginInboxTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PluginInbox');
    }

    public static function getCountMessages($id=null) {
        $q = Doctrine_Query::create()
                ->from('Inbox c')
                ->where('c.record_id = ?', $id);
        return $q->count();
    }

    public static function getParentMessage($record_id=null) {
        $q = Doctrine_Query::create()
                ->from('Inbox c')
                ->where('c.record_id = ?', $record_id)
                ->andWhere('c.reply = ?', false);
        return $q->fetchOne();
    }

    public static function getHasReply($record_id=null) {
        $q = Doctrine_Query::create()
                ->from('Inbox c')
                ->where('c.record_id = ?', $record_id)
                ->andWhere('c.reply = ?', true);
        return $q->count();
    }

    public static function activateReply($id=null) {
        Doctrine_Query::create()
                ->update('Inbox i')
                ->set('i.is_active', '?', true)
                ->where('i.id = ?', $id)
                ->andWhere('i.reply = ?', true)
                ->execute();
    }

}