<?php

/**
 * AudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AudioTable extends PluginAudioTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Audio');
    }
}