<?php

/**
 * Audio_has_playlistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Audio_has_playlistTable extends PluginAudio_has_playlistTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Audio_has_playlistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Audio_has_playlist');
    }
}