<?php

/**
 * FavlikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FavlikeTable extends PluginFavlikeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FavlikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Favlike');
    }
}