<?php

/**
 * PlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistTable extends PluginPlaylistTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaylistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Playlist');
    }
}