<?php

/**
 * PubsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PubsTable extends PluginPubsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PubsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pubs');
    }
}