<?php

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $name
 * @property text $description
 * @property date $date
 * @property time $hour
 * @property date $end_date
 * @property time $end_hour
 * @property boolean $is_active
 * @property string $address
 * @property float $latitude
 * @property float $longitude
 * @property string $image
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getName()        Returns the current record's "name" value
 * @method text        getDescription() Returns the current record's "description" value
 * @method date        getDate()        Returns the current record's "date" value
 * @method time        getHour()        Returns the current record's "hour" value
 * @method date        getEndDate()     Returns the current record's "end_date" value
 * @method time        getEndHour()     Returns the current record's "end_hour" value
 * @method boolean     getIsActive()    Returns the current record's "is_active" value
 * @method string      getAddress()     Returns the current record's "address" value
 * @method float       getLatitude()    Returns the current record's "latitude" value
 * @method float       getLongitude()   Returns the current record's "longitude" value
 * @method string      getImage()       Returns the current record's "image" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Event       setUserId()      Sets the current record's "user_id" value
 * @method Event       setName()        Sets the current record's "name" value
 * @method Event       setDescription() Sets the current record's "description" value
 * @method Event       setDate()        Sets the current record's "date" value
 * @method Event       setHour()        Sets the current record's "hour" value
 * @method Event       setEndDate()     Sets the current record's "end_date" value
 * @method Event       setEndHour()     Sets the current record's "end_hour" value
 * @method Event       setIsActive()    Sets the current record's "is_active" value
 * @method Event       setAddress()     Sets the current record's "address" value
 * @method Event       setLatitude()    Sets the current record's "latitude" value
 * @method Event       setLongitude()   Sets the current record's "longitude" value
 * @method Event       setImage()       Sets the current record's "image" value
 * @method Event       setUser()        Sets the current record's "User" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hour', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('end_hour', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('latitude', 'float', 9, array(
             'type' => 'float',
             'scale' => 7,
             'notnull' => true,
             'length' => 9,
             ));
        $this->hasColumn('longitude', 'float', 9, array(
             'type' => 'float',
             'scale' => 7,
             'notnull' => true,
             'length' => 9,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}