<?php

/**
 * PluginTags_photoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTags_photoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTags_photoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTags_photo');
    }
}