<?php

/**
 * PluginAlbum_photoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAlbum_photoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAlbum_photoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAlbum_photo');
    }

    public static function listAlbumsQuery($params) {
        $q = Doctrine_Query::create()
                        ->select('a.*,sfu.username username,p.*')
                        ->from('Album_photo a')
                        ->leftJoin('a.User sfu')
                        ->leftJoin('a.Photos p')
                        ->where('a.user_id=?', $params['user_id'])
                        ->orderBy('a.ord')
                        ->addOrderBy('a.updated_at DESC')
                        ->addOrderBy('p.ord')
                        ->addOrderBy('p.updated_at DESC');
        return $q;
    }

    public static function listAllAlbums(Doctrine_Query $q){
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.User sfu');
        $q->leftJoin($rootAlias . '.Photos p');
        return $q;
    }

    public static function amountAlbums($params) {
        $q = self::listAlbumsQuery($params);
        return $q->count();
    }

    public static function getLastAlbumQuery($params) {
        $q = Doctrine_Query::create()
                       ->select('a.*,sfu.username username,p.*')
                        ->from('Album_photo a')
                        ->leftJoin('a.User sfu')
                        ->leftJoin('a.Photos p')
                        ->where('a.user_id=?', $params['user_id'])
                        ->orderBy('ord')
                        ->addOrderBy('updated_at DESC')
                        ->limit(1);
        return $q;
    }

    public static function getLastAlbum($params) {
        $q = self::getLastAlbumQuery($params);
        return $q->execute();
    }

    public static function getLastPhoto($params) {
        $q = Doctrine_Query::create()
                        ->from('Photo p')
                        ->where('p.album_id=?', $params['album_id'])
                        ->addOrderBy('created_at DESC')
                        ->limit($params['limit']);
        return $q->execute();
    }

    public static function getOrds($params) {
        $q = Doctrine_Query::create()
                        ->select('p.id, p.ord,p.updated_at')
                        ->from('Photo p')
                        ->where('p.album_id=?', $params['album_id'])
                        ->orderBy('p.ord')
                        ->addOrderBy('updated_at DESC');
        $results = $q->execute();
        $o = array();
        for ($i = 0; $i < count($results); $i++) {
            $next = ($i + 1 < count($results)) ? $i + 1 : 0;
            $prev = ($i - 1 >= 0 ) ? $i - 1 : count($results) - 1;
            $id=$results[$i]->getId();
            $o[$id]['ord'] = $i+1;
            $o[$id]['id'] = $results[$i]->getId();
            $o[$id]['prev'] = $results[$prev]->getId();
            $o[$id]['next'] = $results[$next]->getId();
        }
        return $o;
    }

    public static function deleteComments($params) {
        $q = Doctrine_Query::create()
                        ->delete('Comment')
                        ->where('record_id=?', $params['album_id'])
                        ->addWhere('record_model=?','Album_photo');
        return $q->execute();
    }
}