<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/18 18:48:27
sfConfig::add(array(
  'app_event_commentable' => true,
  'app_event_favlikeable' => true,
  'app_gmaps_js' => 'http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAddW2_j-icZZyAl1A2ya7rhRl5JQqZiZG73MOqcIpjYnqDPNJ5hRvzm7HgwP7-5aGQPDsJNWMYE1-Gw',
  'app_profile_album_name' => 'Profile photos',
  'app_wall_album_name' => 'Wall photos',
  'app_photo_commentable' => true,
  'app_album_commentable' => true,
  'app_photo_favlikeable' => true,
  'app_album_favlikeable' => true,
  'app_audio_commentable' => true,
  'app_audio_favlikeable' => true,
  'app_sf_guard_plugin_success_signin_url' => 'http://social-sandbox/frontend_dev.php',
  'app_base_url' => 'http://social-sandbox/',
  'app_site_name' => 'Social sandbox',
));
