<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/18 18:48:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test_5',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
