<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/09/18 18:49:04
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
