<?php

/**
 * BaseNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $dest_user_id
 * @property string $record_model
 * @property integer $record_id
 * @property string $related_model
 * @property datetime $created_at
 * @property boolean $is_active
 * @property sfGuardUser $User
 * @property sfGuardUser $DestUser
 * 
 * @method integer      getUserId()        Returns the current record's "user_id" value
 * @method integer      getDestUserId()    Returns the current record's "dest_user_id" value
 * @method string       getRecordModel()   Returns the current record's "record_model" value
 * @method integer      getRecordId()      Returns the current record's "record_id" value
 * @method string       getRelatedModel()  Returns the current record's "related_model" value
 * @method datetime     getCreatedAt()     Returns the current record's "created_at" value
 * @method boolean      getIsActive()      Returns the current record's "is_active" value
 * @method sfGuardUser  getUser()          Returns the current record's "User" value
 * @method sfGuardUser  getDestUser()      Returns the current record's "DestUser" value
 * @method Notification setUserId()        Sets the current record's "user_id" value
 * @method Notification setDestUserId()    Sets the current record's "dest_user_id" value
 * @method Notification setRecordModel()   Sets the current record's "record_model" value
 * @method Notification setRecordId()      Sets the current record's "record_id" value
 * @method Notification setRelatedModel()  Sets the current record's "related_model" value
 * @method Notification setCreatedAt()     Sets the current record's "created_at" value
 * @method Notification setIsActive()      Sets the current record's "is_active" value
 * @method Notification setUser()          Sets the current record's "User" value
 * @method Notification setDestUser()      Sets the current record's "DestUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dest_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('record_model', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('record_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('related_model', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => false,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as DestUser', array(
             'local' => 'dest_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}