<?php

/**
 * BaseAudio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $filename
 * @property string $description
 * @property integer $plays
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Audio_has_playlist
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method string              getFilename()           Returns the current record's "filename" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method integer             getPlays()              Returns the current record's "plays" value
 * @method sfGuardUser         getUser()               Returns the current record's "User" value
 * @method Doctrine_Collection getAudioHasPlaylist()   Returns the current record's "Audio_has_playlist" collection
 * @method Audio               setId()                 Sets the current record's "id" value
 * @method Audio               setUserId()             Sets the current record's "user_id" value
 * @method Audio               setFilename()           Sets the current record's "filename" value
 * @method Audio               setDescription()        Sets the current record's "description" value
 * @method Audio               setPlays()              Sets the current record's "plays" value
 * @method Audio               setUser()               Sets the current record's "User" value
 * @method Audio               setAudioHasPlaylist()   Sets the current record's "Audio_has_playlist" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAudio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('audio');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('plays', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Audio_has_playlist', array(
             'local' => 'id',
             'foreign' => 'audio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}