<?php

/**
 * BaseLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $url
 * @property string $image
 * @property string $title
 * @property string $site_name
 * @property string $description
 * @property sfGuardUser $User
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getUrl()         Returns the current record's "url" value
 * @method string      getImage()       Returns the current record's "image" value
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getSiteName()    Returns the current record's "site_name" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Link        setId()          Sets the current record's "id" value
 * @method Link        setUserId()      Sets the current record's "user_id" value
 * @method Link        setUrl()         Sets the current record's "url" value
 * @method Link        setImage()       Sets the current record's "image" value
 * @method Link        setTitle()       Sets the current record's "title" value
 * @method Link        setSiteName()    Sets the current record's "site_name" value
 * @method Link        setDescription() Sets the current record's "description" value
 * @method Link        setUser()        Sets the current record's "User" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('link');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));
        $this->hasColumn('image', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('site_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}